# baseurl = "http://abirger.github.io/sos-guidelines"
baseurl = "http://duncombe.github.io/test-site"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languageCode = "en-us"

Title = "SOS v1.0"

[params]
     Description = "Docs, codes, scripts, templates"
     Copyright = "(C) 2014 U.S. IOOS. Some rights reserved"
